<?php ?>
<div class="field custom<?php if ($block->isRequired()) echo 'required';?>">
    <label class="label" for="<?php echo $block-escapeHtml($block->getFieldId());?>">
        <span><?php echo $block-> escapeHtml($block->getFieldLabel());?></span>
    </label>
    <div class="controll">
        <input type="text"
                id="<?php echo $block->escapeHtml($block->getFieldId()); ?>"
                name="<?php echo $block->escapeHtml($block->getIdFieldName()); ?>"
                value="<?php echo $block->escapeHtml($block->getValue()); ?>"
                title="<?php echo $block->escapeHtml($block->getFieldLabel());  ?>"
                class="input-text"
               <?php echo $block->getFieldsParams()  ?>
            <?php  if($block->isRequired()) echo 'data-validate="{required:true}"' ?> />
        >
        
    </div>
    
    
</div>